move from cra to vite
shootermv/fb-paginated-commits-react18 pull request #157
Opened 2023-08-14 15:20 UTC by SamMrach

2023-08-15 07:08 UTC, shootermv requested changes

2023-08-15 07:08 UTC, shootermv commented on yarn.lock
I perfer not to move from using `yarn` to `npm`... so, can i ask you to try to remove `package.lock` instead of removing `yarn.lock` fike? Nuce work anyway 👍

2023-08-15 20:12 UTC, SamMrach commented on yarn.lock
@shootermv  i used to use npm, i switched to yarn. check it now please.

2023-08-16 05:02 UTC, shootermv commented on yarn.lock
grate job!
The only thong left is- to retore yarn.lock file
with newly added packages
For doing this you need to run `yarn add -D vite vite-plugin-sgr vite-tsconfig-path`

2023-08-16 10:18 UTC, SamMrach commented on yarn.lock
Done, check it now.

2023-08-18 10:14 UTC, shootermv commented on yarn.lock
grate job! i want to merge it ASAP
i can see there are conflicts now, don you want to solve them please?
thanks!

2023-08-20 10:06 UTC, shootermv approved these changes

2023-08-20 10:53 UTC, shootermv approved these changes

2023-08-20 13:01 UTC, merged